#!/usr/bin/env zsh

# Devuan SDK configuration
# safe to leave untouched

# syntax: variable=value
# (no spaces before and after the equal sign)

mirror=https://packages.devuan.org/merged
release=jessie
section=main
version=alpha4


# TODO: make a iso skeleton of our own
iso_mirror=https://vagrant.devuan.org
# amd64/iso-cd/debian-jessie-DI-rc2-amd64-netinst.iso
# amd64/iso-cd/debian-jessie-DI-rc2-i386-netinst.iso
