#!/usr/bin/env zsh

# Devuan SDK configuration
# safe to leave untouched

# syntax: variable=value
# (no spaces before and after the equal sign)

mirror=http://packages.devuan.org/merged
release=jessie
section=main
version=alpha4

base_packages=(bzip2 less dialog zsh sysvinit debian-keyring devuan-keyring)
base_packages+=(apt-utils fakeroot e2fsprogs curl file)

# tools
system_packages=(initramfs-tools parted usbutils binutils ca-certificates u-boot-tools git)
# diagnostics
system_packages+=(htop iotop iftop wavemon)
# usability
system_packages+=(console-common locales tmux screen vim-nox joe nano less)
# networking
system_packages+=(dhcpcd5 openssh-server wpasupplicant)

# keep far from us
exclude_packages=(libsystemd0 systemd systemd-sysv)

# TODO: make a iso skeleton of our own
iso_mirror=https://vagrant.devuan.org
# amd64/iso-cd/debian-jessie-DI-rc2-amd64-netinst.iso
# amd64/iso-cd/debian-jessie-DI-rc2-i386-netinst.iso
