#!/usr/bin/env zsh

# Devuan SDK configuration
# safe to leave untouched

# syntax: variable=value
# (no spaces before and after the equal sign)

mirror=http://ftp.debian.org/debian/
release=jessie
section=main


# TODO change with final release of Debian when ready
iso_mirror=http://mirror.debianfork.org
# amd64/iso-cd/debian-jessie-DI-rc1-amd64-netinst.iso

# deboostrap settings for chroots
chroot_include=bzip2,less,dialog,sysvinit,debian-keyring,apt-utils
# zsh,vim-nox,,xorriso,cpio,xz-utils,dpkg-dev,gcc,g++,autoconf,automake,libtool
chroot_exclude=systemd-sysv
chroot_variant=buildd
chroot_comp=main # components
