#!/usr/bin/env zsh

# Devuan SDK

# Copyright (C) 2015-2016 Dyne.org Foundation
#
# Devuan SDK is written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it and/or
# modify it under the terms of the GNU Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This source code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer
# to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to: Free Software Foundation, Inc.,
# 675 Mass Ave, Cambridge, MA 02139, USA.

# reqs: curl, gnupg2, sudo, schroot, debootstrap


# setup zsh options
setopt pushdsilent

# load zsh modules
zmodload zsh/system
zmodload zsh/regex

# adopts Zsh extension "Zuper"
zkv=1
helpers=1
source zlibs/zuper

## declare global variables

# config variables
vars+=(mirror release section version)
vars+=(chroot_include chroot_exclude chroot_variant chroot_comp)

# global variables
vars+=(R sdk_loaded)

# we assume source sdk is always run from the source dir
# which is the "root" of the program, $R, or env DEVUAN_SDK
R=${DEVUAN_SDK:-`pwd`}

# package import variables
vars+=(source_url)
vars+=(pkg_name q_name q_ver)
vars+=(src_name src_ver src_dest orig_ver)
vars+=(src_orig src_dsc src_debian)
vars+=(staged_ver staged_githead)
arrs+=(src_files)

# global maps (TODO in zuper)
maps+=(hash_map heads casting)

# chroot variables
vars+=(chroot_arch chroot_shell)

# build variables
vars+=(repo_name repo_ver repo_deps build_ver orig_name)

# iso variables
vars+=(iso_arch iso_type iso_img iso_mirror)


source config

# load all zlibs
source zlibs/init
source zlibs/helpers
source zlibs/package
source zlibs/chroot
source zlibs/stage
source zlibs/build
# source zlibs/mirror
source zlibs/iso
source zlibs/packer

# complete zuper initialization
source zlibs/zuper.init

# unset DEBUG_BEFORE_CMD
TRAPDEBUG() {
    RPROMPT="${repo_name:-$src_name} ${repo_ver:-$src_ver} ${chroot_arch} ${iso_type}"
}

# exit on error of any function
TRAPZERR() { zerr; return $? }

if [[ $sdk_loaded = 1 ]]; then
    act "Devuan SDK reloaded"
else
    notice "Devuan SDK loaded"
    typeset -h sdk_loaded
    sdk_loaded=1
    export RPROMPT=Devuan
fi
