#!/bin/sh

echo "Finishing the Devuan VM"

# here set the suit and components to avoid dialogs
echo "devuan-baseconf suite string jessie"      | debconf-set-selections
echo "devuan-baseconf components string main"   | debconf-set-selections
echo "debconf priority select critical"         | debconf-set-selections

apt-get remove --purge -y systemd
apt-get remove --purge -y exim4 exim4-base exim4-config
apt-get remove --purge -y xauth
apt-get remove --purge -y reportbug

apt-get -o Acquire::Check-Valid-Until=false update -y

DEBIAN_FRONTEND='noninteractive' apt-get -o Acquire::Check-Valid-Until=false upgrade -y

apt-get -o Acquire::Check-Valid-Until=false install -y zsh

apt-get -o Acquire::Check-Valid-Until=false install -y guile-2.0

# sudo is needed for vagrant
apt-get -o Acquire::Check-Valid-Until=false install -y sudo

DEBIAN_FRONTEND='noninteractive' apt-get autoremove -y

apt-get clean

echo "debconf priority select medium"         | debconf-set-selections
