#!/bin/sh

print "Finishing the Devuan VM"

apt-get remove --purge -y exim4 exim4-base exim4-config systemd

apt-get -o Acquire::Check-Valid-Until=false upgrade -y

apt-get autoremove -y

apt-get clean
