#!/usr/bin/env zsh

# Devuan SDK - package import management

# Copyright (C) 2015 Dyne.org Foundation
#
# Devuan SDK is designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it and/or
# modify it under the terms of the GNU Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This source code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer
# to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to: Free Software Foundation, Inc.,
# 675 Mass Ave, Cambridge, MA 02139, USA.

init() {
    fn init

    # initialization
    init-repos && init-keyring

    mkdir -p $R/sources
    mkdir -p $R/stage
    mkdir -p $R/chroot
    mkdir -p $R/builds

    notice "Devuan SDK succesfully initialized"
    act "For usage information refer to the README."
    return $?
}

init-repos() {
    fn init-repos

    url="https://git.devuan.org/groups"
    git="https://git.devuan.org/packages-base"
    print "Updating list of Devuan packages"
    repos=`curl -s https://git.devuan.org/groups/packages-base | awk '/a class=.*project/ { print $3}' | cut -d'"' -f2`
    mkdir -p $R/stage
    pushd $R/stage
    for i in ${(f)repos}; do
        base=`basename $i`
        if [[ -d $base ]]; then

            pushd $base
            act "Pull updates for $base"
            git pull
            popd

        else

            act "Cloning new repo for $base"
            git clone ${git}/${base}.git

        fi
    done
    popd
}

init-keyring() {
    fn init-keyring

    [[ -s $R/.gnupg/debian-keyring.gpg ]] && {
        print "Public keyring found."
        return 0
    }

    mkdir -p $R/.gnupg

    pushd $R/.gnupg/
    rsync -az --progress keyring.debian.org::keyrings/keyrings/debian-keyring.gpg .

    print "GnuPG debian maintainers keyring succesfully imported"
    pkg_name=$_pkg_name
    pkg_ver=$_pkg_ver
    popd
}
